#!/usr/bin/env sh
# Platform post-provision (POSIX): rewrite platform/backend/.env and
# platform/frontend/.env.production from azd env values.

set -eu

printf "Platform post-provision: rewriting .env files\n"

hook_dir="$(cd "$(dirname "$0")" && pwd)"
platform_dir="$(cd "$hook_dir/../.." && pwd)"
backend_env="$platform_dir/backend/.env"
frontend_env="$platform_dir/frontend/.env.production"

values_file="$(mktemp)"
azd env get-values > "$values_file"

get_env() {
  name="$1"; default="${2:-}"
  line="$(grep -E "^[[:space:]]*${name}[[:space:]]*=" "$values_file" | head -n1 || true)"
  if [ -z "$line" ]; then printf "%s" "$default"; return; fi
  val="${line#*=}"
  val="$(printf "%s" "$val" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
  case "$val" in
    \"*\") val="${val%\"}"; val="${val#\"}";;
  esac
  printf "%s" "$val"
}

cosmos_endpoint="$(get_env COSMOSDB_ENDPOINT)"
cosmos_db="$(get_env COSMOSDB_DATABASE_NAME)"
cosmos_account="$(get_env COSMOSDB_ACCOUNT_NAME)"
cosmos_catalog="$(get_env COSMOSDB_CATALOG_COLLECTION catalog)"
cosmos_cohorts="$(get_env COSMOSDB_COHORTS_COLLECTION cohorts)"
acr="$(get_env CONTAINER_REGISTRY)"
appi="$(get_env APPLICATIONINSIGHTS_CONNECTION_STRING)"
sub="$(get_env AZURE_SUBSCRIPTION_ID)"
tenant="$(get_env AZURE_TENANT_ID)"
loc="$(get_env AZURE_LOCATION eastus2)"
rg="$(get_env AZURE_RESOURCE_GROUP_NAME)"
apim="$(get_env APIM_GATEWAY_URL)"
env_name="$(get_env AZURE_ENV_NAME)"

cosmos_host="$(printf "%s" "$cosmos_endpoint" | sed -E 's#^https?://([^:/]+).*$#\1#')"
acr_name="$(printf "%s" "$acr" | sed -E 's/\.azurecr\.io$//')"

printf "Writing %s\n" "$backend_env"
cat > "$backend_env" <<EOF
# Generated by platform/_infra/hooks/postprovision.sh
APPINSIGHTS_CONNECTIONSTRING="$appi"
AZURE_CONTAINER_REGISTRY_ENDPOINT="$acr"
AZURE_CONTAINER_REGISTRY_NAME="$acr_name"
AZURE_ENV_NAME="$env_name"
AZURE_LOCATION="$loc"
AZURE_RESOURCE_GROUP="$rg"
AZURE_SUBSCRIPTION_ID="$sub"
AZURE_TENANT_ID="$tenant"

# Cosmos DB (platform stack)
COSMOSDB_DATABASE="$cosmos_db"
COSMOSDB_CATALOG_COLLECTION="$cosmos_catalog"
COSMOSDB_COHORTS_COLLECTION="$cosmos_cohorts"
COSMOSDB_HOST="$cosmos_host"
COSMOS_ACCOUNT_NAME="$cosmos_account"
COSMOS_ENDPOINT="$cosmos_endpoint"

# APIM
APIM_GATEWAY_URL="$apim"

# Local-dev MSAL bypass; never enable in prod
DEVELOPMENT_MODE=true
EOF

if [ -f "$frontend_env" ]; then
  tmp_fe="$(mktemp)"
  grep -v -E '^[[:space:]]*VITE_APIM_GATEWAY_URL[[:space:]]*=' "$frontend_env" > "$tmp_fe" || true
  printf "VITE_APIM_GATEWAY_URL=%s\n" "$apim" >> "$tmp_fe"
  mv "$tmp_fe" "$frontend_env"
  printf "Updated %s (refreshed VITE_APIM_GATEWAY_URL)\n" "$frontend_env"
else
  printf "Skipped frontend .env.production (not present)\n"
fi

rm -f "$values_file"
printf "Platform post-provision complete.\n"
