#!/usr/bin/env bash
# Receivers post-provision: rewrite receivers/backend/.env and
# receivers/frontend/.env.production with the values from this azd env.
#
# Mirrors the providers stack pattern: the AKS-side orchestrator deploy
# (build-and-push + kubectl apply) is intentionally not run here; it is
# handled by an explicit follow-up step after azd up succeeds.

set -euo pipefail

echo "Receivers post-provision: rewriting .env files"

HOOK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RECEIVERS_DIR="$(cd "$HOOK_DIR/../.." && pwd)"
BACKEND_ENV="$RECEIVERS_DIR/backend/.env"
FRONTEND_PROD_ENV="$RECEIVERS_DIR/frontend/.env.production"

echo "Loading azd env values..."
declare -A ENV_VALUES=()
while IFS= read -r line; do
  if [[ "$line" =~ ^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=[[:space:]]*(.*)$ ]]; then
    key="${BASH_REMATCH[1]}"
    val="${BASH_REMATCH[2]}"
    if [[ "$val" =~ ^\"(.*)\"$ ]]; then
      val="${BASH_REMATCH[1]}"
    fi
    ENV_VALUES["$key"]="$val"
  fi
done < <(azd env get-values)

get_env() {
  local key="$1"
  local default="${2:-}"
  if [[ -n "${ENV_VALUES[$key]:-}" ]]; then
    printf '%s' "${ENV_VALUES[$key]}"
  else
    printf '%s' "$default"
  fi
}

COSMOS_ENDPOINT="$(get_env COSMOSDB_ENDPOINT)"
COSMOS_DB="$(get_env COSMOSDB_DATABASE_NAME)"
COSMOS_ACCOUNT="$(get_env COSMOSDB_ACCOUNT_NAME)"
COSMOS_CATALOG="$(get_env COSMOSDB_CATALOG_COLLECTION catalog)"
COSMOS_COHORTS="$(get_env COSMOSDB_COHORTS_COLLECTION cohorts)"
CONTAINER_REGISTRY="$(get_env CONTAINER_REGISTRY)"
APP_INSIGHTS="$(get_env APPLICATIONINSIGHTS_CONNECTION_STRING)"
SUB_ID="$(get_env AZURE_SUBSCRIPTION_ID)"
TENANT_ID="$(get_env AZURE_TENANT_ID)"
LOCATION="$(get_env AZURE_LOCATION eastus2)"
RG_NAME="$(get_env AZURE_RESOURCE_GROUP_NAME)"
APIM_GATEWAY="$(get_env APIM_GATEWAY_URL)"
ENV_NAME="$(get_env AZURE_ENV_NAME)"
SQL_SERVER_NAME="$(get_env AZURE_SQL_SERVER_NAME)"
SQL_DATABASE_NAME="$(get_env AZURE_SQL_DATABASE_NAME)"
SQL_SERVER_FQDN="$(get_env AZURE_SQL_SERVER_FQDN)"
SQL_CONNECTION_STRING="$(get_env AZURE_SQL_CONNECTION_STRING)"

COSMOS_HOST="${COSMOS_ENDPOINT#https://}"
COSMOS_HOST="${COSMOS_HOST#http://}"
COSMOS_HOST="${COSMOS_HOST%%:*}"
COSMOS_HOST="${COSMOS_HOST%%/*}"

ACR_NAME="${CONTAINER_REGISTRY%.azurecr.io}"

echo "Writing $BACKEND_ENV"
cat > "$BACKEND_ENV" <<EOF
# Generated by receivers/_infra/hooks/postprovision.sh
# Edit fields by hand if you need to override an azd output.
APPINSIGHTS_CONNECTIONSTRING="$APP_INSIGHTS"
AZURE_CONTAINER_REGISTRY_ENDPOINT="$CONTAINER_REGISTRY"
AZURE_CONTAINER_REGISTRY_NAME="$ACR_NAME"
AZURE_ENV_NAME="$ENV_NAME"
AZURE_LOCATION="$LOCATION"
AZURE_RESOURCE_GROUP="$RG_NAME"
AZURE_SUBSCRIPTION_ID="$SUB_ID"
AZURE_TENANT_ID="$TENANT_ID"

# Cosmos DB (receivers stack)
COSMOSDB_DATABASE="$COSMOS_DB"
COSMOSDB_CATALOG_COLLECTION="$COSMOS_CATALOG"
COSMOSDB_COHORTS_COLLECTION="$COSMOS_COHORTS"
COSMOSDB_HOST="$COSMOS_HOST"
COSMOS_ACCOUNT_NAME="$COSMOS_ACCOUNT"
COSMOS_ENDPOINT="$COSMOS_ENDPOINT"

# Azure SQL reporting database
AZURE_SQL_SERVER_NAME="$SQL_SERVER_NAME"
AZURE_SQL_DATABASE_NAME="$SQL_DATABASE_NAME"
AZURE_SQL_SERVER_FQDN="$SQL_SERVER_FQDN"
AZURE_SQL_CONNECTION_STRING="$SQL_CONNECTION_STRING"
RECEIVER_REPORTING_SQL_ENABLED=true

# APIM (kept for parity with providers/submitters)
APIM_GATEWAY_URL="$APIM_GATEWAY"

# Local-dev MSAL bypass; never enable in prod
DEVELOPMENT_MODE=true
EOF

if [[ -f "$FRONTEND_PROD_ENV" ]]; then
  echo "Updating $FRONTEND_PROD_ENV (refreshed VITE_APIM_GATEWAY_URL)"
  tmp="$(mktemp)"
  grep -v -E '^\s*VITE_APIM_GATEWAY_URL\s*=' "$FRONTEND_PROD_ENV" > "$tmp" || true
  printf 'VITE_APIM_GATEWAY_URL=%s\n' "$APIM_GATEWAY" >> "$tmp"
  mv "$tmp" "$FRONTEND_PROD_ENV"
else
  echo "Skipped frontend .env.production (not present)"
fi

echo "Receivers post-provision complete."
