table ProcessingEvents
	lineageTag: processing-events

	column ProcessingEventId
		dataType: int64
		sourceColumn: ProcessingEventId

	column CreatedAtUtc
		dataType: dateTime
		sourceColumn: CreatedAtUtc

	column EventType
		dataType: string
		sourceColumn: EventType

	column Status
		dataType: string
		sourceColumn: Status

	column ErrorMessage
		dataType: string
		sourceColumn: ErrorMessage

	column SucceededCount
		dataType: int64
		sourceColumn: SucceededCount

	column TotalCount
		dataType: int64
		sourceColumn: TotalCount

	partition ProcessingEvents = m
		mode: import
		source =
			let
			    Source = Sql.Database(SqlServerName, SqlDatabaseName),
			    Table = Source{[Schema="dq",Item="ProcessingEvents"]}[Data],
			    WithSuccess = Table.AddColumn(Table, "SucceededCount", each if [Status] = "succeeded" then 1 else 0, Int64.Type),
			    WithTotal = Table.AddColumn(WithSuccess, "TotalCount", each 1, Int64.Type)
			in
			    WithTotal
