table ProcessingEvents
	lineageTag: processing-events

	/// Share of receiver processing events that completed successfully.
	measure 'Processing success rate' =
			DIVIDE(
			    SUM('ProcessingEvents'[SucceededCount]),
			    SUM('ProcessingEvents'[TotalCount])
			)
		formatString: 0.0%
		displayFolder: Operations
		lineageTag: 311e9063-bd0c-4850-af3a-bd56e7ff85a3

	/// Number of receiver processing events in the current filter context.
	measure 'Processing events' = SUM('ProcessingEvents'[TotalCount])
		formatString: #,##0
		displayFolder: Operations
		lineageTag: 16d31659-7ec9-49e7-9f4d-a0d830ca060c

	/// Number of receiver processing events that completed successfully.
	measure 'Successful processing events' = SUM('ProcessingEvents'[SucceededCount])
		formatString: #,##0
		displayFolder: Operations
		lineageTag: 18b5bf09-39d9-448e-aa1d-9f850bd5ef88

	/// Number of receiver processing events that did not complete successfully.
	measure 'Failed processing events' = [Processing events] - [Successful processing events]
		formatString: #,##0
		displayFolder: Operations
		lineageTag: 3c82f8fd-4fe0-4d41-86d4-8ba4b9826961

	/// Failed validation events recorded by the receiver.
	measure 'Validation errors' =
			CALCULATE(
			    [Failed processing events],
			    KEEPFILTERS('ProcessingEvents'[EventType] = "Validation")
			)
		formatString: #,##0
		displayFolder: Operations
		lineageTag: dddc5752-2a90-4120-a4aa-2bfd5e2134d1

	/// Average elapsed processing time for events with captured latency.
	measure 'Average latency' = AVERAGE('ProcessingEvents'[LatencyMs])
		formatString: #,##0 "ms"
		displayFolder: Operations\Latency
		lineageTag: 17b7e226-2d48-4838-a875-9d8f1f8cf457

	/// Median elapsed processing time for events with captured latency.
	measure 'Median latency' = MEDIAN('ProcessingEvents'[LatencyMs])
		formatString: #,##0 "ms"
		displayFolder: Operations\Latency
		lineageTag: ec906e40-579c-484b-aa34-30913a1d2821

	/// 95th percentile elapsed processing time for events with captured latency.
	measure 'P95 latency' =
			PERCENTILEX.INC(
			    FILTER(
			        'ProcessingEvents',
			        NOT ISBLANK('ProcessingEvents'[LatencyMs])
			    ),
			    'ProcessingEvents'[LatencyMs],
			    0.95
			)
		formatString: #,##0 "ms"
		displayFolder: Operations\Latency
		lineageTag: ee1b72a9-a76a-46ed-b173-470519c53bac

	column ProcessingEventId
		dataType: int64
		lineageTag: 8b4d9c9b-0a4a-4013-9046-36e6d5bad635
		sourceColumn: ProcessingEventId

	column CreatedAtUtc
		dataType: dateTime
		lineageTag: a5bf5ea0-ec6b-49d4-b7b2-39b0ae5071fd
		sourceColumn: CreatedAtUtc

	column EventType
		dataType: string
		lineageTag: d40b7acd-b395-4392-b87f-5de59e2a69e8
		sourceColumn: EventType

	column Status
		dataType: string
		lineageTag: 7211c2d1-182d-40b9-a5b1-f018ebe24a62
		sourceColumn: Status

	column ErrorMessage
		dataType: string
		lineageTag: 3b74c34c-df65-4141-a90d-dcf27244bf2b
		sourceColumn: ErrorMessage

	column SucceededCount
		dataType: int64
		lineageTag: dc2ebf70-ecdc-48d9-b716-6932ae4fd065
		sourceColumn: SucceededCount

	column TotalCount
		dataType: int64
		lineageTag: 0377c07c-1550-4a6e-b069-e31c7e0e26e6
		sourceColumn: TotalCount

	/// Identifier that links processing events to the originating submission or workbench execution.
	column CorrelationId
		dataType: string
		lineageTag: 25068fd6-18ea-49b0-9d4d-8226bf1b6935
		summarizeBy: none
		sourceColumn: CorrelationId

	/// Quality measure associated with the processing event.
	column MeasureId
		dataType: string
		lineageTag: 757b2019-299a-49df-9a64-ae285a49fa98
		summarizeBy: none
		sourceColumn: MeasureId

	/// Organization associated with the processing event.
	column SubmitterId
		dataType: string
		lineageTag: cda786b3-1775-4f49-b776-6ab339590ce1
		summarizeBy: none
		sourceColumn: SubmitterId

	/// Reporting program associated with the processing event.
	column ProgramId
		dataType: string
		lineageTag: 59ab5bee-8e70-471e-a4b5-a3fa10c6b22c
		summarizeBy: none
		sourceColumn: ProgramId

	/// Elapsed processing time in milliseconds when captured by the receiver.
	column LatencyMs
		dataType: int64
		lineageTag: 4f0d586c-d96d-4307-82b2-fd0725dc6860
		summarizeBy: none
		sourceColumn: LatencyMs

	/// Machine-readable error classification for a failed processing event.
	column ErrorCode
		dataType: string
		lineageTag: 30337006-a046-4f73-8900-b69f31b54b58
		summarizeBy: none
		sourceColumn: ErrorCode

	partition ProcessingEvents = m
		mode: import
		source =
				let
				    SampleData = #table(
				        type table [
				            ProcessingEventId = Int64.Type,
				            CorrelationId = text,
				            CreatedAtUtc = datetime,
				            EventType = text,
				            MeasureId = text,
				            SubmitterId = text,
				            ProgramId = text,
				            Status = text,
				            LatencyMs = Int64.Type,
				            ErrorCode = text,
				            ErrorMessage = text,
				            SucceededCount = Int64.Type,
				            TotalCount = Int64.Type
				        ],
				        {
				            {1, "SUB-1001", #datetime(2026, 1, 8, 9, 16, 0), "Validation", "CMS122", "SUBM-ACME", "MIPS", "succeeded", 420, null, "", 1, 1},
				            {2, "SUB-1002", #datetime(2026, 1, 15, 11, 41, 0), "MeasureCalculation", "CMS165", "SUBM-BAYSTATE", "MIPS", "succeeded", 1250, null, "", 1, 1},
				            {3, "SUB-1003", #datetime(2026, 2, 3, 8, 6, 0), "Validation", "ePC02", "SUBM-CITYCLINIC", "Medicaid", "succeeded", 510, null, "", 1, 1},
				            {4, "SUB-1004", #datetime(2026, 2, 12, 14, 21, 0), "Validation", "CMS122", "SUBM-NORTHWELL", "MedicareAdvantage", "failed", 780, "FHIR_REQUIRED", "Missing required FHIR resource: Patient", 0, 1},
				            {5, "SUB-1005", #datetime(2026, 2, 27, 10, 1, 0), "MeasureCalculation", "CMS165", "SUBM-ACME", "MIPS", "succeeded", 1680, null, "", 1, 1},
				            {6, "SUB-1006", #datetime(2026, 3, 6, 9, 46, 0), "Transformation", "CMS122", "SUBM-BAYSTATE", "Medicaid", "succeeded", 920, null, "", 1, 1},
				            {7, "SUB-1007", #datetime(2026, 3, 19, 13, 31, 0), "Validation", "CMS165", "SUBM-CITYCLINIC", "MIPS", "succeeded", 460, null, "", 1, 1},
				            {8, "SUB-1008", #datetime(2026, 3, 28, 16, 11, 0), "Submission", "ePC02", "SUBM-NORTHWELL", "MedicareAdvantage", "succeeded", 610, null, "", 1, 1},
				            {9, "SUB-1009", #datetime(2026, 4, 9, 8, 51, 0), "MeasureCalculation", "CMS122", "SUBM-ACME", "MIPS", "succeeded", 1420, null, "", 1, 1},
				            {10, "SUB-1010", #datetime(2026, 4, 21, 12, 16, 0), "Transformation", "CMS165", "SUBM-CITYCLINIC", "Medicaid", "succeeded", 870, null, "", 1, 1},
				            {11, "SUB-1011", #datetime(2026, 5, 5, 9, 6, 0), "Validation", "ePC02", "SUBM-BAYSTATE", "MIPS", "failed", 830, "TERMINOLOGY_BINDING", "Terminology binding error: invalid LOINC code", 0, 1},
				            {12, "SUB-1012", #datetime(2026, 5, 18, 15, 26, 0), "MeasureCalculation", "CMS122", "SUBM-NORTHWELL", "MedicareAdvantage", "succeeded", 2150, null, "", 1, 1},
				            {13, "SUB-1013", #datetime(2026, 5, 29, 11, 1, 0), "Submission", "CMS165", "SUBM-ACME", "MIPS", "succeeded", 590, null, "", 1, 1},
				            {14, "SUB-1014", #datetime(2026, 6, 11, 10, 36, 0), "Validation", "CMS122", "SUBM-BAYSTATE", "Medicaid", "succeeded", 440, null, "", 1, 1},
				            {15, "SUB-1015", #datetime(2026, 6, 24, 14, 51, 0), "MeasureCalculation", "ePC02", "SUBM-CITYCLINIC", "MIPS", "succeeded", 1880, null, "", 1, 1}
				        }
				    ),
				    LiveData =
				        let
				            Source = Sql.Database(SqlServerName, SqlDatabaseName),
				            Table = Source{[Schema="dq",Item="ProcessingEvents"]}[Data],
				            WithSuccess = Table.AddColumn(Table, "SucceededCount", each if [Status] = "succeeded" then 1 else 0, Int64.Type),
				            WithTotal = Table.AddColumn(WithSuccess, "TotalCount", each 1, Int64.Type)
				        in
				            WithTotal,
				    Result = if UseSampleData then SampleData else LiveData
				in
				    Result
