#!/usr/bin/env sh
# Submitters post-provision (POSIX): rewrite submitters/backend/.env and
# submitters/frontend/.env.production from azd env values. AKS-side build/push
# and kubectl steps are intentionally not run here.

set -eu

printf "Submitters post-provision: rewriting .env files\n"

hook_dir="$(cd "$(dirname "$0")" && pwd)"
submitters_dir="$(cd "$hook_dir/../.." && pwd)"
backend_env="$submitters_dir/backend/.env"
frontend_env="$submitters_dir/frontend/.env.production"
orch_env="$submitters_dir/orchestrator/.env"

values_file="$(mktemp)"
azd env get-values > "$values_file"

get_env() {
  name="$1"; default="${2:-}"
  line="$(grep -E "^[[:space:]]*${name}[[:space:]]*=" "$values_file" | head -n1 || true)"
  if [ -z "$line" ]; then printf "%s" "$default"; return; fi
  val="${line#*=}"
  val="$(printf "%s" "$val" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
  case "$val" in
    \"*\") val="${val%\"}"; val="${val#\"}";;
  esac
  printf "%s" "$val"
}

cosmos_endpoint="$(get_env COSMOSDB_ENDPOINT)"
cosmos_db="$(get_env COSMOSDB_DATABASE_NAME)"
cosmos_account="$(get_env COSMOSDB_ACCOUNT_NAME)"
cosmos_catalog="$(get_env COSMOSDB_CATALOG_COLLECTION catalog)"
cosmos_cohorts="$(get_env COSMOSDB_COHORTS_COLLECTION cohorts)"
acr="$(get_env CONTAINER_REGISTRY)"
appi="$(get_env APPLICATIONINSIGHTS_CONNECTION_STRING)"
sub="$(get_env AZURE_SUBSCRIPTION_ID)"
tenant="$(get_env AZURE_TENANT_ID)"
loc="$(get_env AZURE_LOCATION eastus2)"
rg="$(get_env AZURE_RESOURCE_GROUP_NAME)"
apim="$(get_env APIM_GATEWAY_URL)"
env_name="$(get_env AZURE_ENV_NAME)"

cosmos_host="$(printf "%s" "$cosmos_endpoint" | sed -E 's#^https?://([^:/]+).*$#\1#')"
acr_name="$(printf "%s" "$acr" | sed -E 's/\.azurecr\.io$//')"

write_env() {
  target="$1"; label="$2"
  printf "Writing %s\n" "$target"
  cat > "$target" <<EOF
# Generated by submitters/_infra/hooks/postprovision.sh ($label)
APPINSIGHTS_CONNECTIONSTRING="$appi"
AZURE_CONTAINER_REGISTRY_ENDPOINT="$acr"
AZURE_CONTAINER_REGISTRY_NAME="$acr_name"
AZURE_ENV_NAME="$env_name"
AZURE_LOCATION="$loc"
AZURE_RESOURCE_GROUP="$rg"
AZURE_SUBSCRIPTION_ID="$sub"
AZURE_TENANT_ID="$tenant"

# Cosmos DB (submitters stack)
COSMOSDB_DATABASE="$cosmos_db"
COSMOSDB_CATALOG_COLLECTION="$cosmos_catalog"
COSMOSDB_COHORTS_COLLECTION="$cosmos_cohorts"
COSMOSDB_HOST="$cosmos_host"
COSMOS_ACCOUNT_NAME="$cosmos_account"
COSMOS_ENDPOINT="$cosmos_endpoint"

# APIM
APIM_GATEWAY_URL="$apim"

# Local-dev MSAL bypass; never enable in prod
DEVELOPMENT_MODE=true
EOF
}

write_env "$backend_env" "backend"
if [ -f "$orch_env" ] || [ -d "$submitters_dir/orchestrator" ]; then
  write_env "$orch_env" "orchestrator"
fi

if [ -f "$frontend_env" ]; then
  tmp_fe="$(mktemp)"
  grep -v -E '^[[:space:]]*VITE_APIM_GATEWAY_URL[[:space:]]*=' "$frontend_env" > "$tmp_fe" || true
  printf "VITE_APIM_GATEWAY_URL=%s\n" "$apim" >> "$tmp_fe"
  mv "$tmp_fe" "$frontend_env"
  printf "Updated %s (refreshed VITE_APIM_GATEWAY_URL)\n" "$frontend_env"
else
  printf "Skipped frontend .env.production (not present)\n"
fi

rm -f "$values_file"
printf "Submitters post-provision complete.\n"
