#!/usr/bin/env pwsh
# Submitters post-provision: rewrite submitters/backend/.env and
# submitters/frontend/.env.production with the values from this azd env.
#
# Mirrors the providers/receivers minimal pattern. The AKS-side
# orchestrator deploy (build-and-push + kubectl apply) is intentionally
# not run here; that is a follow-up step after azd up succeeds.

param()

$ErrorActionPreference = 'Stop'

Write-Host "Submitters post-provision: rewriting .env files" -ForegroundColor Cyan

$hookDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$submittersDir = Resolve-Path (Join-Path $hookDir '..' '..')
$backendEnvPath = Join-Path $submittersDir 'backend\.env'
$frontendProdEnvPath = Join-Path $submittersDir 'frontend\.env.production'
$orchestratorEnvPath = Join-Path $submittersDir 'orchestrator\.env'

Write-Host "Loading azd env values..."
$envValues = @{}
$lines = azd env get-values
foreach ($line in $lines) {
  if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$') {
    $key = $matches[1]
    $val = $matches[2].Trim()
    if ($val.StartsWith('"') -and $val.EndsWith('"')) {
      $val = $val.Substring(1, $val.Length - 2)
    }
    $envValues[$key] = $val
  }
}

function Get-Env([string]$name, [string]$default = '') {
  if ($envValues.ContainsKey($name)) { return $envValues[$name] }
  return $default
}

$cosmosEndpoint = Get-Env 'COSMOSDB_ENDPOINT'
$cosmosDb = Get-Env 'COSMOSDB_DATABASE_NAME'
$cosmosAccount = Get-Env 'COSMOSDB_ACCOUNT_NAME'
$cosmosCatalog = Get-Env 'COSMOSDB_CATALOG_COLLECTION' 'catalog'
$cosmosCohorts = Get-Env 'COSMOSDB_COHORTS_COLLECTION' 'cohorts'
$containerRegistry = Get-Env 'CONTAINER_REGISTRY'
$appInsights = Get-Env 'APPLICATIONINSIGHTS_CONNECTION_STRING'
$subscriptionId = Get-Env 'AZURE_SUBSCRIPTION_ID'
$tenantId = Get-Env 'AZURE_TENANT_ID'
$location = Get-Env 'AZURE_LOCATION' 'eastus2'
$rgName = Get-Env 'AZURE_RESOURCE_GROUP_NAME'
$apimGateway = Get-Env 'APIM_GATEWAY_URL'

$cosmosHost = ''
if ($cosmosEndpoint -match '^https?://([^:/]+)') { $cosmosHost = $matches[1] }

$backendEnvLines = @(
  '# Generated by submitters/_infra/hooks/postprovision.ps1',
  '# Edit fields by hand if you need to override an azd output.',
  "APPINSIGHTS_CONNECTIONSTRING=`"$appInsights`"",
  "AZURE_CONTAINER_REGISTRY_ENDPOINT=`"$containerRegistry`"",
  "AZURE_CONTAINER_REGISTRY_NAME=`"$($containerRegistry -replace '\.azurecr\.io$', '')`"",
  "AZURE_ENV_NAME=`"$(Get-Env 'AZURE_ENV_NAME')`"",
  "AZURE_LOCATION=`"$location`"",
  "AZURE_RESOURCE_GROUP=`"$rgName`"",
  "AZURE_SUBSCRIPTION_ID=`"$subscriptionId`"",
  "AZURE_TENANT_ID=`"$tenantId`"",
  '',
  '# Cosmos DB (submitters stack)',
  "COSMOSDB_DATABASE=`"$cosmosDb`"",
  "COSMOSDB_CATALOG_COLLECTION=`"$cosmosCatalog`"",
  "COSMOSDB_COHORTS_COLLECTION=`"$cosmosCohorts`"",
  "COSMOSDB_HOST=`"$cosmosHost`"",
  "COSMOS_ACCOUNT_NAME=`"$cosmosAccount`"",
  "COSMOS_ENDPOINT=`"$cosmosEndpoint`"",
  '',
  '# APIM',
  "APIM_GATEWAY_URL=`"$apimGateway`"",
  '',
  '# Local-dev MSAL bypass; never enable in prod',
  'DEVELOPMENT_MODE=true'
)

Write-Host "Writing $backendEnvPath"
$backendEnvLines -join "`n" | Set-Content -Path $backendEnvPath -Encoding utf8 -NoNewline
Add-Content -Path $backendEnvPath -Value "" -NoNewline

if (Test-Path $orchestratorEnvPath) {
  $orchEnv = $backendEnvLines | ForEach-Object { $_ -replace '^# Generated by submitters/_infra/hooks/postprovision.ps1','# Generated by submitters/_infra/hooks/postprovision.ps1 (orchestrator)' }
  Write-Host "Writing $orchestratorEnvPath"
  $orchEnv -join "`n" | Set-Content -Path $orchestratorEnvPath -Encoding utf8 -NoNewline
  Add-Content -Path $orchestratorEnvPath -Value "" -NoNewline
}

if (Test-Path $frontendProdEnvPath) {
  $existing = Get-Content -Path $frontendProdEnvPath
  $kept = $existing | Where-Object { $_ -notmatch '^\s*VITE_APIM_GATEWAY_URL\s*=' }
  $kept += "VITE_APIM_GATEWAY_URL=$apimGateway"
  $kept -join "`n" | Set-Content -Path $frontendProdEnvPath -Encoding utf8 -NoNewline
  Add-Content -Path $frontendProdEnvPath -Value "" -NoNewline
  Write-Host "Updated $frontendProdEnvPath (refreshed VITE_APIM_GATEWAY_URL)"
}
else {
  Write-Host "Skipped frontend .env.production (not present)"
}

Write-Host "Submitters post-provision complete." -ForegroundColor Green
