#!/usr/bin/env bash
# Providers post-provision: rewrite providers/backend/.env and
# providers/frontend/.env.production with the values from this azd env.
#
# The providers stack has no orchestrator; it only needs to know how to
# reach its own Cosmos DB + ACR + App Insights, plus the submitters
# orchestrator URL (kept as DIGITAL_QUALITY_ORCHESTRATOR_BASE_URL).

set -euo pipefail

echo "Providers post-provision: rewriting .env files"

HOOK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROVIDERS_DIR="$(cd "$HOOK_DIR/../.." && pwd)"
BACKEND_ENV="$PROVIDERS_DIR/backend/.env"
FRONTEND_PROD_ENV="$PROVIDERS_DIR/frontend/.env.production"

# Load azd env values into shell variables. azd env get-values prints
# KEY="value" lines.
echo "Loading azd env values..."
declare -A ENV_VALUES=()
while IFS= read -r line; do
  if [[ "$line" =~ ^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=[[:space:]]*(.*)$ ]]; then
    key="${BASH_REMATCH[1]}"
    val="${BASH_REMATCH[2]}"
    # strip surrounding double quotes
    if [[ "$val" =~ ^\"(.*)\"$ ]]; then
      val="${BASH_REMATCH[1]}"
    fi
    ENV_VALUES["$key"]="$val"
  fi
done < <(azd env get-values)

get_env() {
  local key="$1"
  local default="${2:-}"
  if [[ -n "${ENV_VALUES[$key]:-}" ]]; then
    printf '%s' "${ENV_VALUES[$key]}"
  else
    printf '%s' "$default"
  fi
}

COSMOS_ENDPOINT="$(get_env COSMOSDB_ENDPOINT)"
COSMOS_DB="$(get_env COSMOSDB_DATABASE_NAME)"
COSMOS_ACCOUNT="$(get_env COSMOSDB_ACCOUNT_NAME)"
COSMOS_CATALOG="$(get_env COSMOSDB_CATALOG_COLLECTION catalog)"
COSMOS_COHORTS="$(get_env COSMOSDB_COHORTS_COLLECTION cohorts)"
CONTAINER_REGISTRY="$(get_env CONTAINER_REGISTRY)"
APP_INSIGHTS="$(get_env APPLICATIONINSIGHTS_CONNECTION_STRING)"
SUB_ID="$(get_env AZURE_SUBSCRIPTION_ID)"
TENANT_ID="$(get_env AZURE_TENANT_ID)"
LOCATION="$(get_env AZURE_LOCATION eastus2)"
RG_NAME="$(get_env AZURE_RESOURCE_GROUP_NAME)"
APIM_GATEWAY="$(get_env APIM_GATEWAY_URL)"
ENV_NAME="$(get_env AZURE_ENV_NAME)"

# Strip scheme from cosmos endpoint for legacy COSMOSDB_HOST.
COSMOS_HOST="${COSMOS_ENDPOINT#https://}"
COSMOS_HOST="${COSMOS_HOST#http://}"
COSMOS_HOST="${COSMOS_HOST%%:*}"
COSMOS_HOST="${COSMOS_HOST%%/*}"

ACR_NAME="${CONTAINER_REGISTRY%.azurecr.io}"

echo "Writing $BACKEND_ENV"
cat > "$BACKEND_ENV" <<EOF
# Generated by providers/_infra/hooks/postprovision.sh
# Edit fields by hand if you need to override an azd output.
APPINSIGHTS_CONNECTIONSTRING="$APP_INSIGHTS"
AZURE_CONTAINER_REGISTRY_ENDPOINT="$CONTAINER_REGISTRY"
AZURE_CONTAINER_REGISTRY_NAME="$ACR_NAME"
AZURE_ENV_NAME="$ENV_NAME"
AZURE_LOCATION="$LOCATION"
AZURE_RESOURCE_GROUP="$RG_NAME"
AZURE_SUBSCRIPTION_ID="$SUB_ID"
AZURE_TENANT_ID="$TENANT_ID"

# Cosmos DB (providers stack)
COSMOSDB_DATABASE="$COSMOS_DB"
COSMOSDB_CATALOG_COLLECTION="$COSMOS_CATALOG"
COSMOSDB_COHORTS_COLLECTION="$COSMOS_COHORTS"
COSMOSDB_HOST="$COSMOS_HOST"
COSMOS_ACCOUNT_NAME="$COSMOS_ACCOUNT"
COSMOS_ENDPOINT="$COSMOS_ENDPOINT"

# APIM (kept for parity with submitters)
APIM_GATEWAY_URL="$APIM_GATEWAY"

# Local-dev MSAL bypass; never enable in prod
DEVELOPMENT_MODE=true

# Submitters orchestrator URL (cross-stack). Override per environment.
# Local-compose default lands at host.docker.internal:8001.
DIGITAL_QUALITY_ORCHESTRATOR_BASE_URL=http://host.docker.internal:8001
EOF

if [[ -f "$FRONTEND_PROD_ENV" ]]; then
  echo "Updating $FRONTEND_PROD_ENV (refreshed VITE_APIM_GATEWAY_URL)"
  tmp="$(mktemp)"
  grep -v -E '^\s*VITE_APIM_GATEWAY_URL\s*=' "$FRONTEND_PROD_ENV" > "$tmp" || true
  printf 'VITE_APIM_GATEWAY_URL=%s\n' "$APIM_GATEWAY" >> "$tmp"
  mv "$tmp" "$FRONTEND_PROD_ENV"
else
  echo "Skipped frontend .env.production (not present)"
fi

# ---------------------------------------------------------------------------
# Seed Quality Measures Workbench data into Cosmos.
#
# Mirrors the receivers stack pattern: dev IP firewall opening + dev Cosmos
# Data Contributor RBAC are wired in main.bicep (developerIpAddress /
# developerPrincipalId), so the seeder can run from the dev workstation
# against the private Cosmos account using DefaultAzureCredential.
#
# Requires DEVELOPER_IP_ADDRESS and DEVELOPER_PRINCIPAL_ID in the azd env so
# the firewall rule and role assignment land. Without them, the upserts will
# fail with 403 or network errors. Failures are non-fatal so provision still
# completes; rerun manually after fixing the env.
# ---------------------------------------------------------------------------
REPO_ROOT="$(cd "$PROVIDERS_DIR/.." && pwd)"
SEED_SCRIPT="$REPO_ROOT/_scripts/seed_workbench_data.py"
DATA_DIR_PATH="$REPO_ROOT/_data"

if [[ -f "$SEED_SCRIPT" ]]; then
  echo ""
  echo "Seeding Quality Measures Workbench data into Cosmos DB..."
  export COSMOSDB_ENDPOINT="$COSMOS_ENDPOINT"
  export COSMOSDB_DATABASE_NAME="$COSMOS_DB"
  export COSMOSDB_CATALOG_COLLECTION="$COSMOS_CATALOG"
  export COSMOSDB_COHORTS_COLLECTION="$COSMOS_COHORTS"
  export DATA_DIR="$DATA_DIR_PATH"
  # Force UTF-8 stdout so the seeder's non-ASCII status output stays consistent.
  export PYTHONIOENCODING=utf-8
  if ! python "$SEED_SCRIPT"; then
    echo "  Workbench seed failed. Rerun manually: python $SEED_SCRIPT"
  else
    echo "  Workbench seed complete"
  fi
else
  echo "Skipped workbench seed (script not found at $SEED_SCRIPT)"
fi

echo "Providers post-provision complete."
