#!/usr/bin/env pwsh
# Providers post-provision: rewrite providers/backend/.env and
# providers/frontend/.env.production with the values from this azd env.
#
# The providers stack has no orchestrator; it only needs to know how to
# reach its own Cosmos DB + ACR + App Insights, plus the submitters
# orchestrator URL (kept as DIGITAL_QUALITY_ORCHESTRATOR_BASE_URL).

param()

$ErrorActionPreference = 'Stop'

Write-Host "Providers post-provision: rewriting .env files" -ForegroundColor Cyan

# Resolve repo paths relative to this script.
$hookDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$providersDir = Resolve-Path (Join-Path $hookDir '..' '..')
$backendEnvPath = Join-Path $providersDir 'backend\.env'
$frontendProdEnvPath = Join-Path $providersDir 'frontend\.env.production'

# Pull azd env values.
Write-Host "Loading azd env values..."
$envValues = @{}
$lines = azd env get-values
foreach ($line in $lines) {
  if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$') {
    $key = $matches[1]
    $val = $matches[2].Trim()
    if ($val.StartsWith('"') -and $val.EndsWith('"')) {
      $val = $val.Substring(1, $val.Length - 2)
    }
    $envValues[$key] = $val
  }
}

function Get-Env([string]$name, [string]$default = '') {
  if ($envValues.ContainsKey($name)) { return $envValues[$name] }
  return $default
}

$cosmosEndpoint = Get-Env 'COSMOSDB_ENDPOINT'
$cosmosDb = Get-Env 'COSMOSDB_DATABASE_NAME'
$cosmosAccount = Get-Env 'COSMOSDB_ACCOUNT_NAME'
$cosmosCatalog = Get-Env 'COSMOSDB_CATALOG_COLLECTION' 'catalog'
$cosmosCohorts = Get-Env 'COSMOSDB_COHORTS_COLLECTION' 'cohorts'
$containerRegistry = Get-Env 'CONTAINER_REGISTRY'
$appInsights = Get-Env 'APPLICATIONINSIGHTS_CONNECTION_STRING'
$subscriptionId = Get-Env 'AZURE_SUBSCRIPTION_ID'
$tenantId = Get-Env 'AZURE_TENANT_ID'
$location = Get-Env 'AZURE_LOCATION' 'eastus2'
$rgName = Get-Env 'AZURE_RESOURCE_GROUP_NAME'
$apimGateway = Get-Env 'APIM_GATEWAY_URL'

# Pull Cosmos host (without scheme) from the endpoint for legacy COSMOSDB_HOST.
$cosmosHost = ''
if ($cosmosEndpoint -match '^https?://([^:/]+)') { $cosmosHost = $matches[1] }

# Compose the new backend .env.
$backendEnvLines = @(
  '# Generated by providers/_infra/hooks/postprovision.ps1',
  '# Edit fields by hand if you need to override an azd output.',
  "APPINSIGHTS_CONNECTIONSTRING=`"$appInsights`"",
  "AZURE_CONTAINER_REGISTRY_ENDPOINT=`"$containerRegistry`"",
  "AZURE_CONTAINER_REGISTRY_NAME=`"$($containerRegistry -replace '\.azurecr\.io$', '')`"",
  "AZURE_ENV_NAME=`"$(Get-Env 'AZURE_ENV_NAME')`"",
  "AZURE_LOCATION=`"$location`"",
  "AZURE_RESOURCE_GROUP=`"$rgName`"",
  "AZURE_SUBSCRIPTION_ID=`"$subscriptionId`"",
  "AZURE_TENANT_ID=`"$tenantId`"",
  '',
  '# Cosmos DB (providers stack)',
  "COSMOSDB_DATABASE=`"$cosmosDb`"",
  "COSMOSDB_CATALOG_COLLECTION=`"$cosmosCatalog`"",
  "COSMOSDB_COHORTS_COLLECTION=`"$cosmosCohorts`"",
  "COSMOSDB_HOST=`"$cosmosHost`"",
  "COSMOS_ACCOUNT_NAME=`"$cosmosAccount`"",
  "COSMOS_ENDPOINT=`"$cosmosEndpoint`"",
  '',
  '# APIM (kept for parity with submitters)',
  "APIM_GATEWAY_URL=`"$apimGateway`"",
  '',
  '# Local-dev MSAL bypass; never enable in prod',
  'DEVELOPMENT_MODE=true',
  '',
  '# Submitters orchestrator URL (cross-stack). Override per environment.',
  '# Local-compose default lands at host.docker.internal:8001.',
  'DIGITAL_QUALITY_ORCHESTRATOR_BASE_URL=http://host.docker.internal:8001'
)

Write-Host "Writing $backendEnvPath"
$backendEnvLines -join "`n" | Set-Content -Path $backendEnvPath -Encoding utf8 -NoNewline
Add-Content -Path $backendEnvPath -Value "" -NoNewline

# Compose the new frontend .env.production. VITE_AZURE_* values are not in
# azd outputs (they come from the Entra app registration); we only refresh the
# bits we can compute. The rest stay as whatever was last written by hand.
if (Test-Path $frontendProdEnvPath) {
  $existing = Get-Content -Path $frontendProdEnvPath
  $kept = $existing | Where-Object { $_ -notmatch '^\s*VITE_APIM_GATEWAY_URL\s*=' }
  $kept += "VITE_APIM_GATEWAY_URL=$apimGateway"
  $kept -join "`n" | Set-Content -Path $frontendProdEnvPath -Encoding utf8 -NoNewline
  Add-Content -Path $frontendProdEnvPath -Value "" -NoNewline
  Write-Host "Updated $frontendProdEnvPath (refreshed VITE_APIM_GATEWAY_URL)"
}
else {
  Write-Host "Skipped frontend .env.production (not present)"
}

# ---------------------------------------------------------------------------
# Seed Quality Measures Workbench data into Cosmos.
#
# Mirrors the receivers stack pattern: dev IP firewall opening + dev Cosmos
# Data Contributor RBAC are wired in main.bicep (developerIpAddress /
# developerPrincipalId), so the seeder can run from the dev workstation
# against the private Cosmos account using DefaultAzureCredential.
#
# Requires DEVELOPER_IP_ADDRESS and DEVELOPER_PRINCIPAL_ID in the azd env so
# the firewall rule and role assignment land. Without them, the upserts will
# fail with 403 or network errors. Failures are non-fatal so provision still
# completes; rerun manually after fixing the env.
# ---------------------------------------------------------------------------
$repoRoot = Resolve-Path (Join-Path $providersDir '..')
$seedScript = Join-Path $repoRoot '_scripts\seed_workbench_data.py'
$dataDir = Join-Path $repoRoot '_data'

if (Test-Path $seedScript) {
  Write-Host "`nSeeding Quality Measures Workbench data into Cosmos DB..." -ForegroundColor Cyan
  $env:COSMOSDB_ENDPOINT = $cosmosEndpoint
  $env:COSMOSDB_DATABASE_NAME = $cosmosDb
  $env:COSMOSDB_CATALOG_COLLECTION = $cosmosCatalog
  $env:COSMOSDB_COHORTS_COLLECTION = $cosmosCohorts
  $env:DATA_DIR = $dataDir
  # Force UTF-8 stdout so the seeder's non-ASCII status emoji don't trip cp1252 on Windows.
  $env:PYTHONIOENCODING = 'utf-8'
  python $seedScript
  if ($LASTEXITCODE -eq 0) {
    Write-Host "  Workbench seed complete" -ForegroundColor Green
  }
  else {
    Write-Host "  Workbench seed failed (exit $LASTEXITCODE). Rerun manually: python $seedScript" -ForegroundColor Yellow
  }
}
else {
  Write-Host "Skipped workbench seed (script not found at $seedScript)" -ForegroundColor Yellow
}

Write-Host "Providers post-provision complete." -ForegroundColor Green
